//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeBook.Communication.EmployeeBookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private EmployeeBook.Communication.EmployeeBookService.DepartmentCategory DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public EmployeeBook.Communication.EmployeeBookService.DepartmentCategory Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((this.DepartmentField.Equals(value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentCategory", Namespace="http://tempuri.org/")]
    public enum DepartmentCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department1 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department2 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department3 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department4 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department5 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeBookService.EmployeebookServiceSoap")]
    public interface EmployeebookServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем LoadResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        EmployeeBook.Communication.EmployeeBookService.LoadResponse Load(EmployeeBook.Communication.EmployeeBookService.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.LoadResponse> LoadAsync(EmployeeBook.Communication.EmployeeBookService.LoadRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        EmployeeBook.Communication.EmployeeBookService.UpdateResponse Update(EmployeeBook.Communication.EmployeeBookService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.UpdateResponse> UpdateAsync(EmployeeBook.Communication.EmployeeBookService.UpdateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        EmployeeBook.Communication.EmployeeBookService.DeleteResponse Delete(EmployeeBook.Communication.EmployeeBookService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.DeleteResponse> DeleteAsync(EmployeeBook.Communication.EmployeeBookService.DeleteRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        EmployeeBook.Communication.EmployeeBookService.AddResponse Add(EmployeeBook.Communication.EmployeeBookService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.AddResponse> AddAsync(EmployeeBook.Communication.EmployeeBookService.AddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Load", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.LoadRequestBody Body;
        
        public LoadRequest() {
        }
        
        public LoadRequest(EmployeeBook.Communication.EmployeeBookService.LoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadRequestBody {
        
        public LoadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.LoadResponseBody Body;
        
        public LoadResponse() {
        }
        
        public LoadResponse(EmployeeBook.Communication.EmployeeBookService.LoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.Employee[] LoadResult;
        
        public LoadResponseBody() {
        }
        
        public LoadResponseBody(EmployeeBook.Communication.EmployeeBookService.Employee[] LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(EmployeeBook.Communication.EmployeeBookService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.Employee employee;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(EmployeeBook.Communication.EmployeeBookService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(EmployeeBook.Communication.EmployeeBookService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.Employee employee;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(EmployeeBook.Communication.EmployeeBookService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(int DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(EmployeeBook.Communication.EmployeeBookService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.Employee employee;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeBook.Communication.EmployeeBookService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(EmployeeBook.Communication.EmployeeBookService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeebookServiceSoapChannel : EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeebookServiceSoapClient : System.ServiceModel.ClientBase<EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap>, EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap {
        
        public EmployeebookServiceSoapClient() {
        }
        
        public EmployeebookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeebookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeebookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeebookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeBook.Communication.EmployeeBookService.LoadResponse EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.Load(EmployeeBook.Communication.EmployeeBookService.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public EmployeeBook.Communication.EmployeeBookService.Employee[] Load() {
            EmployeeBook.Communication.EmployeeBookService.LoadRequest inValue = new EmployeeBook.Communication.EmployeeBookService.LoadRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.LoadRequestBody();
            EmployeeBook.Communication.EmployeeBookService.LoadResponse retVal = ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).Load(inValue);
            return retVal.Body.LoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.LoadResponse> EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.LoadAsync(EmployeeBook.Communication.EmployeeBookService.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.LoadResponse> LoadAsync() {
            EmployeeBook.Communication.EmployeeBookService.LoadRequest inValue = new EmployeeBook.Communication.EmployeeBookService.LoadRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.LoadRequestBody();
            return ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).LoadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeBook.Communication.EmployeeBookService.UpdateResponse EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.Update(EmployeeBook.Communication.EmployeeBookService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.UpdateRequest inValue = new EmployeeBook.Communication.EmployeeBookService.UpdateRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.UpdateRequestBody();
            inValue.Body.employee = employee;
            EmployeeBook.Communication.EmployeeBookService.UpdateResponse retVal = ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.UpdateResponse> EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.UpdateAsync(EmployeeBook.Communication.EmployeeBookService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.UpdateResponse> UpdateAsync(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.UpdateRequest inValue = new EmployeeBook.Communication.EmployeeBookService.UpdateRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.UpdateRequestBody();
            inValue.Body.employee = employee;
            return ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeBook.Communication.EmployeeBookService.DeleteResponse EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.Delete(EmployeeBook.Communication.EmployeeBookService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public int Delete(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.DeleteRequest inValue = new EmployeeBook.Communication.EmployeeBookService.DeleteRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.DeleteRequestBody();
            inValue.Body.employee = employee;
            EmployeeBook.Communication.EmployeeBookService.DeleteResponse retVal = ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.DeleteResponse> EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.DeleteAsync(EmployeeBook.Communication.EmployeeBookService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.DeleteResponse> DeleteAsync(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.DeleteRequest inValue = new EmployeeBook.Communication.EmployeeBookService.DeleteRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.DeleteRequestBody();
            inValue.Body.employee = employee;
            return ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeBook.Communication.EmployeeBookService.AddResponse EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.Add(EmployeeBook.Communication.EmployeeBookService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.AddRequest inValue = new EmployeeBook.Communication.EmployeeBookService.AddRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.AddRequestBody();
            inValue.Body.employee = employee;
            EmployeeBook.Communication.EmployeeBookService.AddResponse retVal = ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.AddResponse> EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap.AddAsync(EmployeeBook.Communication.EmployeeBookService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeBook.Communication.EmployeeBookService.AddResponse> AddAsync(EmployeeBook.Communication.EmployeeBookService.Employee employee) {
            EmployeeBook.Communication.EmployeeBookService.AddRequest inValue = new EmployeeBook.Communication.EmployeeBookService.AddRequest();
            inValue.Body = new EmployeeBook.Communication.EmployeeBookService.AddRequestBody();
            inValue.Body.employee = employee;
            return ((EmployeeBook.Communication.EmployeeBookService.EmployeebookServiceSoap)(this)).AddAsync(inValue);
        }
    }
}
